import "server-only";

import type { StartupIntakeData } from "@gsk/domain";

/** A single uploaded document, base64-encoded (never logged — root CLAUDE.md invariant 6). */
export interface ExtractionDocument {
  name: string;
  mimeType: "application/pdf" | "image/png" | "image/jpeg";
  base64Content: string;
}

export interface ExtractionContradiction {
  /** e.g. "pitch deck says $2M ARR; financial statement shows $1.4M ARR." */
  description: string;
  sourceDocuments: string[];
}

export interface ExtractionResult {
  /**
   * Deliberately `Partial` and deliberately *not* validated against
   * `startupIntakeDataSchema` here — this module's only job is turning
   * documents into a best-effort draft a human founder reviews and
   * corrects before it is ever submitted through
   * submitStartupIntakeCommand, which re-validates from scratch. Nothing
   * from this module is ever persisted directly.
   */
  data: Partial<StartupIntakeData>;
  /** Fields the model could not find in the supplied documents. */
  warnings: string[];
  /** Numbers that disagree across the supplied documents — see ADR 0008. */
  contradictions: ExtractionContradiction[];
}

/**
 * Turns a founder's uploaded documents into a draft `StartupIntakeData`.
 * See ADR 0008 (vendor choice, disclosure, data-residency gap) and ADR
 * 0009 (retention). Never called with a real production document until
 * ZDR is confirmed per ADR 0008's consequences section.
 */
export interface ExtractionProvider {
  extractStartupIntake(documents: ExtractionDocument[]): Promise<ExtractionResult>;
}

export class ExtractionNotConfiguredError extends Error {
  constructor() {
    super(
      "Document extraction is not configured: ANTHROPIC_API_KEY is not set. " +
        "See docs/adr/0008-ai-document-extraction-provider.md — this key must be " +
        "generated by the project owner from their own Anthropic Console account " +
        "and added to Vercel's environment variables; no one else can supply it.",
    );
    this.name = "ExtractionNotConfiguredError";
  }
}

export class ExtractionResponseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ExtractionResponseError";
  }
}
